# Generated by Django 3.2.4 on 2021-06-25 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('ShortName', models.CharField(max_length=100, null=True)),
                ('Describe', models.TextField(blank=True, max_length=4000, null=True)),
                ('Version', models.CharField(max_length=100)),
                ('StartWorkingDay', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ElementOfCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ELementCode', models.CharField(max_length=100)),
                ('ElementValue', models.CharField(max_length=200)),
                ('ElementCatalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CatalogForCurrentElement', to='komtek.catalog')),
            ],
        ),
    ]
