# Generated by Django 3.2.4 on 2021-06-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komtek', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementofcatalog',
            old_name='ELementCode',
            new_name='ElementCode',
        ),
    ]
