# Generated by Django 3.2.4 on 2021-06-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komtek', '0002_rename_elementcode_elementofcatalog_elementcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElementOfCatalog',
            new_name='ElementsOfCatalog',
        ),
        migrations.RenameField(
            model_name='elementsofcatalog',
            old_name='ElementCatalog',
            new_name='Catalog',
        ),
    ]
