# Generated by Django 3.2.4 on 2021-06-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komtek', '0004_alter_catalog_startworkingday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementsofcatalog',
            old_name='Catalog',
            new_name='CatalogInElement',
        ),
    ]
