# Generated by Django 3.2.4 on 2021-06-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komtek', '0005_rename_catalog_elementsofcatalog_cataloginelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementsofcatalog',
            name='CatalogInElement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='komtek.catalog'),
        ),
    ]
